server:
  port: 8092
spring:
  datasource:
    url: jdbc:mysql://1.117.96.29:3306/online?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: 1.117.96.29
    port: 6389
    password: 123456
mybatis:
  mapper-locations: classpath:/mapper/*.xml
logging:
  path: /aresoft/api/log
  config: classpath:logback-spring.xml